# Use an official Python runtime as a parent image
FROM python:3.6

# Adding backend directory to make absolute filepaths consistent across services
WORKDIR /app/server

# Install Python dependencies
COPY Server/requirements.txt /app/server
RUN pip3 install --upgrade pip -r requirements.txt
RUN pip3 install daphne

# Add the rest of the code
COPY ./Server /app/server

# Make port 8000 available for the app
EXPOSE 8000

CMD daphne -b 0.0.0.0 -p 8000 angels_of_delta_server.asgi:application